# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Release
description: Prepare a new release for the project.
title: "[Release] Prepare v<VERSION> release"
labels:
  - Release
assignees:
  - glektarssza
body:
  - type: markdown
    attributes:
      value: |
        Please do **NOT** use this issue template unless you are somebody who
        has the ability to perform a release.

        Abuse of this template **WILL** lead to you getting blocked from being
        able to contribute to this repository/project and, potentially, future
        projects too.

        You have been warned!
  - type: textarea
    attributes:
      label: Body
      description: The body of the issue.
      value: |
        Prepare to release the v<VERSION> release.

        Perform the following steps (in order):

        * [ ] Update the Forge update manifest with change log.
        * [ ] Update the Forge update manifest to point to v0.12.0 as the latest version.
        * [ ] Mark the GitHub milestone as completed.
        * [ ] Tag the release.
        * [ ] Release on GitHub.

        After the above is completed, perform the following steps (in any order):

        * [ ] Release on CurseForge.
        * [ ] Release on Modrinth.
