# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Release
on:
  workflow_dispatch:
    inputs:
      artifacts-id:
        description: |
          The ID of the artifact to release.
        type: string
        required: true
      artifacts-name:
        description: |
          The name of the artifact to release.
        type: string
        required: true
jobs:
  release:
    name: Release
    uses: ./.github/workflows/release.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    with:
      artifacts-id: ${{inputs.artifacts-id}}
      artifacts-name: ${{inputs.artifacts-name}}
