# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Manual Build
on:
  workflow_dispatch:
    inputs:
      build-tag:
        description: |
          The tag to build for.

          Defaults to the current commit SHA (in unique, shortened format).
        type: string
        required: false
        default: ""
      build-config:
        description: |
          The configuration to build for.

          Defaults to `dev`.

          Valid options are:
            * `dev`
            * `prod`
        type: string
        required: true
        default: dev
      verbose-logging:
        description: |
          Whether to enable verbose logging.

          Defaults to `false`.
        type: boolean
        required: false
        default: false
      debug-logging:
        description: |
          Whether to enable debug logging.

          Defaults to `false`.
        type: boolean
        required: false
        default: false
      upload-artifacts:
        description: |
          Whether to upload artifacts from the build.

          Defaults to `false`.
        type: boolean
        required: false
        default: false
      artifact-retention-days:
        description: |
          The number of days to retain uploaded artifacts for.

          Using `0` defaults to the repository's defaults.
        type: number
        required: false
        default: 0
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    with:
      build-tag: ${{inputs.build-tag}}
      build-config: ${{inputs.build-config}}
      verbose-logging: ${{inputs.verbose-logging}}
      debug-logging: ${{inputs.debug-logging}}
      upload-artifacts: ${{inputs.upload-artifacts}}
      artifact-retention-days: ${{inputs.artifact-retention-days}}
