# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: On Pull Request
on:
  pull_request:
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    secrets:
      github-token: ${{secrets.GITHUB_TOKEN}}
    with:
      build-config: prod
      upload-artifacts: true
