# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release
on:
  workflow_call:
    inputs:
      artifacts-id:
        description: |
          The ID of the artifact to release.
        type: string
        required: true
      artifacts-name:
        description: |
          The name of the artifact to release.
        type: string
        required: true
    secrets:
      github-token:
        description: |
          The token to use for making authenticated GitHub API calls.
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      #-- To clone repository and write release artifacts
      contents: write
    steps:
      - id: clone-repository
        name: Clone repository
        uses: actions/checkout@v4
        with:
          show-progress: true
          clean: true
          fetch-tags: true
          fetch-depth: 1
          lfs: true
          submodules: recursive
          token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: download-artifacts
        name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          artifact-ids: ${{inputs.artifacts-id}}
          path: artifacts
          github-token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
      - id: generate-checksums
        name: Generate checksums
        run: |
          md5sum ${{steps.download-artifacts.outputs.download-path}}/${{inputs.artifacts-name}}/* > checksums_md5.txt
          shasum -a 1 ${{steps.download-artifacts.outputs.download-path}}/${{inputs.artifacts-name}}/* > checksums_sha1.txt
          shasum -a 256 ${{steps.download-artifacts.outputs.download-path}}/${{inputs.artifacts-name}}/* > checksums_sha256.txt
          mv *.txt ${{steps.download-artifacts.outputs.download-path}}
      - id: attach-to-release
        name: Attach artifacts to release
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./.github/scripts/upload-release-assets.js');
            await script({github, context, core}, ${{toJson(steps.download-artifacts.outputs.download-path)}});
          github-token: ${{secrets.github-token || secrets.GITHUB_TOKEN}}
